title: "Muhammad Umair"
author: "Muhammad Umair"
description: "Personal portfolio and article collection"
permalink: /blog/:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: false               # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:
  - {file: "index.md", title: "Home", sidebaricon: home}
  - {file: "blog.md", title: "Articles", sidebaricon: book-open}
  - {file: "about.md", title: "About", sidebaricon: user}
  - {file: "contact.md", title: "Contact", sidebaricon: envelope}
  
external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:2025bscpe134@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/umair93905"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
